# Generated by Django 4.0.1 on 2022-02-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_razor_pay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
